### PR TITLE
Add feed

### PR DESCRIPTION
**Pull request by runeunhjem**
Looking for a collaborator to look through and give real comments on the code.

Missing my own posts yet so no messages on my profile.

Added feed posts to the site.
I use Lorem Picsum for images where avatar is missing.

Please comment on flaws, suggestions or errors :)

### CODE REVIEW

**Comment by kimrm** [comment]
I would try to break profile_posts.js into smaller functions or components. It's a lot of code there. Other than that, I don't see much issues. Will look a little more later. Good job 👍

**Comment by runeunhjem** [comment]
> I would try to break profile_posts.js into smaller functions or components. It's a lot of code there. Other than that, I don't see much issues. Will look a little more later. Good job 👍

I'm thinking that is a great idea - on the agenda

**Comment by kyrregjerstad** [comment]
Hey Rune,

Great work on the pull request! The code is clean and the logic is solid. I have a few suggestions that are more in the realm of _"best practices"_ or _"code improvements"_ rather than hard requirements. Feel free to consider these points to further enhance your code.

---

#### **Global Variables**

Consider creating a separate file for global variables like URLs and tokens. This way, they can be managed and updated more easily.

```js
// consts.js

// URLs
export const API_BASE_URL = "https://api.noroff.dev";
// ... other constants
```

---

#### **Separation of Concerns**

You've started doing this in some parts, but how about making each function responsible for a single task? For example, separating the data fetching and HTML element creation logic could make the code even more maintainable.

---

#### **File Structure**

How about having separate files for defining functions and invoking them? You could export the functions and then combine them in a `main.js` or another page-specific file.

---

#### **Error Handling**

You've already incorporated try/catch blocks, which is great. However, consider adding user notifications for errors. This way, the end user is not left in the dark if something goes wrong.

---

#### **Variable Declarations**

I noticed some instances of using `let` where `const` could work just as well. Maybe review these and switch to `const` if the variables are not being reassigned?

---

#### **Form Handling**

Take a look at the [FormData() API](https://developer.mozilla.org/en-US/docs/Web/API/FormData). It's a more elegant way of handling form data in JavaScript, as opposed to using `getElementById` and such.

---

As always, feel free to reach out if you have any questions or if something is unclear. Keep up the good work! 😊

**Comment by runeunhjem** [comment]
> Hey Rune,
> 
> Great work on the pull request! The code is clean and the logic is solid. I have a few suggestions that are more in the realm of _"best practices"_ or _"code improvements"_ rather than hard requirements. Feel free to consider these points to further enhance your code.
> 
> #### **Global Variables**
> Consider creating a separate file for global variables like URLs and tokens. This way, they can be managed and updated more easily.
> 
> ```js
> // consts.js
> 
> // URLs
> export const API_BASE_URL = "https://api.noroff.dev";
> // ... other constants
> ```
> 
> #### **Separation of Concerns**
> You've started doing this in some parts, but how about making each function responsible for a single task? For example, separating the data fetching and HTML element creation logic could make the code even more maintainable.
> 
> #### **File Structure**
> How about having separate files for defining functions and invoking them? You could export the functions and then combine them in a `main.js` or another page-specific file.
> 
> #### **Error Handling**
> You've already incorporated try/catch blocks, which is great. However, consider adding user notifications for errors. This way, the end user is not left in the dark if something goes wrong.
> 
> #### **Variable Declarations**
> I noticed some instances of using `let` where `const` could work just as well. Maybe review these and switch to `const` if the variables are not being reassigned?
> 
> #### **Form Handling**
> Take a look at the [FormData() API](https://developer.mozilla.org/en-US/docs/Web/API/FormData). It's a more elegant way of handling form data in JavaScript, as opposed to using `getElementById` and such.
> 
> As always, feel free to reach out if you have any questions or if something is unclear. Keep up the good work! 😊

Awesome feedback! Thank you!

**Comment by HansMariusAndreassen** [comment]
I think this looks good. I don't really have anything to add to the already given comments :) Good job Rune!!

**Comment by MariuszRozycki** [comment]
Hei.
I'm writing this comment a little bit late, but I see, that you have implemented all of suggestions people gave you. You made a good job. Congrats :)

**Pull request merged**
